// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./components/Footer.vue')['default']
    LoginForm: typeof import('./components/loginForm.vue')['default']
    README: typeof import('./components/README.md')['default']
    RegisterForm: typeof import('./components/registerForm.vue')['default']
  }
}

export { }
