// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    Footer: typeof import('./components/Footer.vue')['default']
    LoginForm: typeof import('./components/loginForm.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    Plum: typeof import('./components/Plum.vue')['default']
    README: typeof import('./components/README.md')['default']
    RegisterForm: typeof import('./components/registerForm.vue')['default']
    Solution: typeof import('./components/taskType/Solution.vue')['default']
    TaskCard: typeof import('./components/TaskCard.vue')['default']
    TaskFooter: typeof import('./components/TaskFooter.vue')['default']
    Trade: typeof import('./components/taskType/Trade.vue')['default']
    WishTask: typeof import('./components/WishTask.vue')['default']
  }
}

export { }
